Wikia/vignette

src/vignette/api/legacy/routes.clj
src/vignette/http/routes.clj
src/vignette/util/regex.clj
test/vignette/api/legacy/routes_test.clj
test/vignette/http/routes_test.clj

@drsnyder @frankfarmer 
Sometimes, you want to have negative offsets.

allow negative offsets in window-crop and window-crop-fixed modes

---

src/vignette/api/legacy/routes.clj
src/vignette/media_types.clj
src/vignette/util/query_options.clj
test/vignette/api/legacy/routes_test.clj
test/vignette/media_types_test.clj

@drsnyder 
https://wikia-inc.atlassian.net/browse/PLATFORM-824
add support for `zone` in both legacy and vignette routes. This is the Vignette side of https://github.com/Wikia/app/pull/6135

don't let me get in my zone

---

src/vignette/api/legacy/routes.clj
src/vignette/http/middleware.clj
src/vignette/http/routes.clj
test/vignette/api/legacy/routes_test.clj

@drsnyder 
I know all about math. https://www.youtube.com/watch?v=7f97_DYDbbM
Adds support for legacy math extension image route. Also adds the `referer` header when logging a bad request path.

What You Know About Math?

---

src/vignette/http/middleware.clj
src/vignette/util/thumbnail.clj
test/vignette/util/thumbnail_test.clj

@drsnyder 
https://wikia-inc.atlassian.net/browse/PLATFORM-883
we can't thumbnail video/audio files :(

have a blacklist of content-types that we can't thumbnail

---

src/vignette/util/image_response.clj

@drsnyder 
https://wikia-inc.atlassian.net/browse/PLATFORM-881
so people who save images don't think we didn't apply their custom format.

add custom format to content disposition header

---

README.md

Add Macbre to the contributors list.
/cc @macbre

Add Macbre to the contributors list

---

test/vignette/http/integration_test.clj
test/vignette/http/legacy/integration_test.clj

* Fixed the port
* Fixed the max-age settings
/cc @nmonterroso @michalroszka

Fix the integration tests

---

README.md

Added Mix to the contributors.
/cc @nmonterroso @michalroszka

Update the contributors

---

project.clj
src/vignette/storage/local.clj
src/vignette/storage/protocols.clj
src/vignette/storage/s3.clj
src/vignette/util/image_response.clj
test/vignette/util/image_response_test.clj

This PR only adds etag header and not If-None-Match check that would return 304 if etags match.
My Vignette/Clojure fu needs some more fine tuning for that.
In next PR I'd also like to HEAD method so that it will return the same set of headers as GET.
/cc: @nmonterroso @drsnyder

PLATFORM-1267: add etag to response headers

---

README.md

Add Pawel to the contributors list.
/cc @pchojnacki @nmonterroso

Add Pawel to the contributors list

---

README.md
src/vignette/storage/s3.clj

A lot of timouts are happening especially around the time when thumbnails are GC'ed this attempts to alleviate this issue
/cc: @adamw-wikia @michalroszka @macbre @wladekb

OPS-7063 increase timeouts and add documentation about them

---

src/vignette/storage/local.clj
src/vignette/storage/s3.clj
src/vignette/system.clj
src/vignette/util/filesystem.clj
src/vignette/util/image_response.clj
src/vignette/util/thumbnail.clj
test/vignette/storage/s3_test.clj
test/vignette/util/image_response_test.clj
test/vignette/util/thumbnail_test.clj

this PR includes fixes for bug introduced in #99 
Addtionally I added better handling of content disposition headers that might be utf-8 encoded

PLATFORM-1541 Fix vignette SVG image scaling

---

bin/thumbnail

this should fix problems with special  chars in filenames as well as mitigate potential attack vector

PLATFORM-1843 make imagick argument handling stop using evals

---

src/vignette/util/image_response.clj
test/vignette/util/image_response_test.clj

[SUS-77](https://wikia-inc.atlassian.net/browse/SUS-77)
/cc: @macbre

SUS-77: Etag quoted string

---

project.clj
resources/log4j.properties
src/vignette/util/thumb_verifier.clj
src/vignette/util/thumbnail.clj
test/vignette/util/thumb_verifier_test.clj
test/vignette/util/thumbnail_test.clj

[Ticket](https://wikia-inc.atlassian.net/browse/SER-81)
This PR introduces a check of the generated thumbnail's size, so that it's possible to investigate potential errors (if any).
//cc @pchojnacki

Ser 81 thumb verifier

---

README.md
resources/logback.xml
src/vignette/util/thumb_verifier.clj
test/vignette/util/thumb_verifier_test.clj

[Ticket](https://wikia-inc.atlassian.net/browse/SER-81)
This PR fixes issues with logging messages, the path to `identify`, and adds missing estimators (for thumbnail modes that are not mentioned in the documentation for Vignette).
//cc @pchojnacki

SER-81 thumb verifier

---

src/vignette/storage/static_assets.clj
src/vignette/util/query_options.clj
src/vignette/util/services.clj
test/vignette/storage/static_assets_test.clj
test/vignette/util/query_options_test.clj
test/vignette/util/services_test.clj

Vignette can forward only status query params to image-review

SER-532 Adds forwarding status query params to image-review

---

src/vignette/setup.clj
src/vignette/storage/static_assets.clj
src/vignette/util/services.clj
test/vignette/storage/static_assets_test.clj
test/vignette/util/services_test.clj

[Ticket](https://wikia-inc.atlassian.net/browse/SER-647)
Removed `image-review` usage
//cc @Wikia/services-team

SER-647 remove image-review usage

---

Dockerfile

ping: @Wikia/services-team, @Wikia/core-platform-team

Initial Dockerfile for Vignette

---

src/vignette/http/legacy/route_helpers.clj
src/vignette/http/legacy/routes.clj
src/vignette/http/route_helpers.clj
src/vignette/media_types.clj
test/vignette/http/legacy/integration_test.clj
test/vignette/http/legacy/routes_test.clj
test/vignette/media_types_test.clj

ping: @Wikia/core-platform-team

Platform-2890 webp for legacy

---

src/vignette/storage/s3.clj
src/vignette/util/image_response.clj
test/vignette/http/legacy/integration_test.clj

https://wikia-inc.atlassian.net/browse/SER-897
Added explicit closing of the S3Object stream passed to the response, which should hopefully prevent blocked connections. Added logging for connection pool timeout.
@Wikia/services-team

SER-897 wrap response in piped-input-stream, log pool timeout

---

Dockerfile-k8s
k8s/k8s_descriptor-poz-dev.yaml

modifying docker image so that we use the same versions of libraries as on our "bare metal" instances.

SER-2714 | better docker image

---

Dockerfile-k8s

bc is used for rescaling images by -down crops

---

src/vignette/http/routes.clj
src/vignette/perfmonitoring/core.clj

add 10s 20s 30s buckets to http request metrics
@Wikia/services-team

Extend histogram buckets
