README.md
src/vignette/storage/s3.clj

If we have a failed HTTP request into CEPH don't bother retrying. There appears to be an issue in the S3 client that introduces additional latency when the error retry count is > 0. Under load, this can backup vignette and connections on the borders.
https://wikia-inc.atlassian.net/browse/PLATFORM-690
/cc @nmonterroso @frankfarmer

Set default max-retries to 0

---

src/vignette/storage/local.clj
src/vignette/storage/protocols.clj
src/vignette/storage/s3.clj
src/vignette/util/integration.clj
test/vignette/util/integration_test.clj

This PR fixes the integration setup. A while back I added `(i/create-integration-env)` which will create a local integration data directory that could be used with `vignette.storage.local`. I must have broken it back when we moved the `transfer!` logic from a multi-method into a protocol.
This PR moves the `transfer!` method into a separate protocol called `TransferableProtocol ` so that the native `java.io.File` abstraction can be `extend`ed to support the `transfer!` method natively. This is the [expression problem](http://www.ibm.com/developerworks/library/j-clojure-protocols/) which clojure provides a nice solution to. Clojure, I :heart: you.
/cc @nmonterroso @owend just for the love

Fix integration setup by separating out the transfer! method into a new protocol

---

src/vignette/http/routes.clj
src/vignette/util/image_response.clj

@drsnyder 
https://wikia-inc.atlassian.net/browse/PLATFORM-632
Add a `Content-Disposition` header so "save as..." dialogs have a hint of the filename to use when saving. Tested in Chrome and Firefox and works as expected. Note that the `filename=` part is kept for user agents that don't support [RFC 5987](https://tools.ietf.org/html/rfc5987), which in my testing it seems that Firefox does not.

add Content-Disposition header for images

---

src/vignette/util/image_response.clj

@drsnyder 
https://wikia-inc.atlassian.net/browse/PLATFORM-751
I think special characters were causing the `filename*=UTF-8' '%s` to break vignette requests in Chrome. Looks like Chrome respects utf-8 characters in `filename="%s"`.

remove filename*= portion of Content-Disposition header

---

src/vignette/util/thumbnail.clj

@drsnyder 
https://wikia-inc.atlassian.net/browse/PLATFORM-759
Sometimes things work but they tell you they didn't. Underpromise, overdeliver I guess.

ImageMagick working but returning exit code 1

---

src/vignette/api/legacy/routes.clj
src/vignette/http/routes.clj
src/vignette/media_types.clj
test/vignette/api/legacy/routes_test.clj
test/vignette/media_types_test.clj

This is another one-off request path supported by the legacy thumbnailer. Here is an [example](http://img2.wikia.nocookie.net/__cb1422289387/television/es/images/timeline/bbe457792492f1b89f21a45aa6ca6088.png) image taken from [here](http://es.television.wikia.com/wiki/Wikivisi%C3%B3n:Administraci%C3%B3n). The paths take the form `/bucket/language/images/timeline/hash.png`. The way we decided to handle this was to allow any of the `:middle-dir` or `:top-dir` paths to be empty.
https://wikia-inc.atlassian.net/browse/MAIN-3622
/cc @nmonterroso @owend (since Nelson might be out)

MAIN-3622 Timeline legacy support

---

src/vignette/http/routes.clj
test/vignette/http/routes_test.clj

It was originally believed that the issue with [favicons](https://wikia-inc.atlassian.net/browse/PLATFORM-667) was the result of the `/revision/latest...` at the end of the favicon link tag. This appears [not to be the case](http://www.google.com/s2/favicons?domain=thelongdark.wikia.com) since [other vignette enabled sites](http://despicableme.wikia.com/wiki/Despicable_Me_Wiki) do not appear to have the same issue.
This PR makes originals directly addressable via `/images/top/middle/original.ext` (drops `/revision/latests`). It also provides some refactoring of `routes` to removed duplicated logic and more tests.
https://wikia-inc.atlassian.net/browse/PLATFORM-667
/cc @nmonterroso

PLATFORM-667 directly addressible originals

---

bin/thumbnail

@drsnyder 
https://wikia-inc.atlassian.net/browse/PLATFORM-808
The density stuff was originally added for [PLATFORM-608](https://wikia-inc.atlassian.net/browse/PLATFORM-608). 200 JIRA issues later, this is causing issues in SVGs that are downsized from the originals. In those cases, from my testing it seems OK to ignore the density stuff.

only apply density magic when upsizing an image

---

src/vignette/http/routes.clj
src/vignette/media_types.clj
src/vignette/util/image_response.clj
test/vignette/http/routes_test.clj
test/vignette/util/external_hotlinking_test.clj
test/vignette/util/image_response_test.clj

Add `Surrogate-Key` header to all image requests. This will enable more effective purging. The surrogate key is derived from the original image path on ceph including the bucket.
This will need to be integrated into MediaWiki. I'm also considering dialing down the `max-age` that we return so that images aren't cached "forever". That has broader implications though so this should be a good stop gap for handling DMCA requests.
https://wikia-inc.atlassian.net/browse/MAIN-3701
/cc @nmonterroso @ljagiello

MAIN-3701 Add 'Surrogate-Key' header to image requests

---

project.clj
src/vignette/util/image_response.clj
test/vignette/http/routes_test.clj
test/vignette/media_types_test.clj
test/vignette/util/image_response_test.clj

Use the hash of the original path as the surrogate key instead of just the original path. There may be some limitations on the size of the key we can use and this should ensure that we comply.
/cc @pchojnacki @nmonterroso

Use the hash of the original path as the surrogate key

---

src/vignette/http/middleware.clj
src/vignette/http/routes.clj

This increments a counter and logs the path whenever we drop into the 404/not-found handler in the routes. This should log any path that does not match the legacy or new style URLs.
/cc @frankfarmer @ljagiello @nmonterroso

Log the bad request paths

---

src/vignette/api/legacy/routes.clj
src/vignette/http/routes.clj
src/vignette/media_types.clj
test/vignette/api/legacy/routes_test.clj

Interactive maps stores images in the following forms which do not map to any of the currently known legacy image paths:
```
/intmap_tile_set_4823/20150205173220!phpZDfa00.jpg
/intmap_tile_set_4823/thumb/20150205173220%21phpZDfa00.jpg/1110x300x5-20150205173220%21phpZDfa00.jpg
/intmap_tile_set_4692/3/1/2.png
```
To support this we need to add explicit legacy support for these paths while also making the path generation code more tolerant of missing fields. 
This PR:
* Adds legacy routes to support interactive maps
* Makes the path generation more tolerant of empty fields
* Adds tests off the new routes
Issue [MWEB-1100](https://wikia-inc.atlassian.net/browse/MWEB-1100) is a side effect of moving all of the legacy traffic to vignette. See https://github.com/Wikia/chef-repo/pull/4197.
/cc …

MWEB-1100 Add legacy routes for interactive maps

---

bin/find-images.js

@drsnyder 
Should help with all those "the path bugs have been fixed but we're waiting for Fastly cache to expire" issues we've been having lately.

adding find-images.js script to easily find vignette images on web pages

---

src/vignette/api/legacy/routes.clj
src/vignette/http/routes.clj
test/vignette/api/legacy/routes_test.clj

Add custom route for imaps markers. They take the form of `/intmap_markers_\d+/<file>`. The `<file>` portion starts with strings of the form `\d+px-<file>` but they are not thumbnailed.
https://wikia-inc.atlassian.net/browse/MAIN-3808
/cc @nmonterroso @rogatty

Add custom route for imaps markers

---

src/vignette/api/legacy/routes.clj
test/vignette/api/legacy/routes_test.clj

Do not add the format to the options if the thumbnail extension is the same as the original. This should result in a closer mapping between legacy file names and new file names. 
There is still more work to be done to make it easier to test this, but this should at least eliminate the unnecessary addition of `[format=foo]` into the legacy filenames when no format changes are taking place.
https://wikia-inc.atlassian.net/browse/MAIN-3931
/cc @ljagiello @nmonterroso

MAIN-3931 Do not add the format to the filename if thumb extension is the same as the original

---

src/vignette/util/thumbnail.clj
test/vignette/util/thumbnail_test.clj

This could prevent 2 round trips to CEPH by short circuiting the thumbnailing sooner. First check the name of the original before we go to CEPH and reject it if it's unsupported. Next, check again in the original location before we attempt to thumbnail the original (this is after the original has been downloaded).
This could catch supported files that happened to be mislabeled e.g. a JPEG labeled `.ogv`. In practice I doubt this happens that often. The opposite is also true but will be handled by the current implementation. That is there could be some OGG video files with the .jpg extension. We'll still catch these when the image is on disk locally.
https://wikia-inc.atlassian.net/browse/MAIN-3930
/cc @nmonterroso @ljagiello

MAIN-3930 Check the mime time to see if it can be thumbnailed earlier in the call stack

---

src/vignette/api/legacy/routes.clj
src/vignette/util/query_options.clj
test/vignette/api/legacy/routes_test.clj

There are some legacy requests that attempt to thumbnail videos using `mid-<video>.ogv.jpg`. This enables sane handling of those requests with a broken image placeholder and a 404.
https://wikia-inc.atlassian.net/browse/PLATFORM-912
/cc @nmonterroso @ljagiello

Provide sane defaults for videos using mid-* in the thumbnail filename

---

README.md
src/vignette/http/routes.clj
test/vignette/http/routes_test.clj
test/vignette/media_types_test.clj
test/vignette/util/external_hotlinking_test.clj
test/vignette/util/image_response_test.clj

There were a few things that stood out to me as I was working on [the duplicate file issue (PLATFORM-940)](https://wikia-inc.atlassian.net/browse/PLATFORM-940). One was that the way we handle the generation of the `image-params` was significantly different between the legacy handling and the vignette handling. The second was that I was pretty sure we were generating other duplicate files other than `[format=ext]`.
This PR addresses both issues. First, the `image-params` map generation has been made more consistent. As a result it's now possible to test that a legacy URI and a new URI that we expect to generate the same thumbnail path in fact to so. See the tests that were added. As a result, this uncovered a difference in how the parameters were being computed for the window cropping in …

Consistent request map handling between old and new URI

---

bin/thumbnail

We are currently requiring the --height param even though some of the thumbnailing modes do not require it. I'm pulling this over from #71 since that PR is going to be ditched in favor of adding `HEAD`.
/cc @nmonterroso

Only require --height when necessary

---

.midje.clj
dev/user.clj
project.clj
src/vignette/http/legacy/route_helpers.clj
src/vignette/http/legacy/routes.clj
src/vignette/http/route_helpers.clj
src/vignette/http/routes.clj
src/vignette/system.clj
test/vignette/http/legacy/integration_test.clj
test/vignette/http/legacy/routes_test.clj
test/vignette/http/route_helpers_test.clj
test/vignette/http/routes_test.clj
test/vignette/media_types_test.clj
test/vignette/util/external_hotlinking_test.clj
test/vignette/util/image_response_test.clj

This is a follow-up to the feedback [here](https://github.com/Wikia/vignette/pull/75#discussion_r25633018).
This PR attempts to simplify our routing namespaces by moving the helper functions out into a separate namespace. This should reduce the clutter and make the main `http.routes` namespace more cohesive.
I also started an experiment with a very simple integration test to see if it works in travis. If it does we can add more to make sure that the API remains stable and ensure that the correct headers are in place. I think our test coverage is decent, but insufficient when making changes that affect the outermost part of the request stack like the handler as in the case with this PR.
/cc @nmonterroso

Refactor routes namespaces to move the helper functions out

---

bin/thumbnail
src/vignette/util/query_options.clj

@drsnyder 
https://wikia-inc.atlassian.net/browse/PLATFORM-984
Requested by @alistra and @aniaMu, this allows thumbnails to be created from specific frames from animated gifs by passing `frame=N` as a query parameter, where `N` is any number between 0 and the count of frames in the image.
TODO:

Capture Still Frame From Animated Image

---

README.md
dev/user.clj
src/vignette/http/route_helpers.clj
src/vignette/http/routes.clj
src/vignette/storage/core.clj
src/vignette/storage/local.clj
src/vignette/storage/protocols.clj
src/vignette/storage/s3.clj
src/vignette/util/image_response.clj
test/vignette/http/integration_test.clj
test/vignette/storage/core_test.clj
test/vignette/storage/local_test.clj
test/vignette/storage/s3_test.clj

This PR adds `HEAD` support to vignette routes to satisfy the vignette side the new purger integration. This turned out to be a little more complicated than expected and the behavior depends upon the order of the route definition. Specifically `HEAD` needs to be defined before `GET` because of [this block in compojure](https://github.com/weavejester/compojure/blob/639fffd3f8b77153644d0c9b87bca5af56be0cb0/src/compojure/core.clj#L28).
One way to handle `HEAD` is to set the `:body` to `nil` in a `GET` request. It looks like this is a shortcut that is imposed by compojure. This is probably fine in the case of materialized bodies but could be problematic when working with file streams as we are.
This might be an pre-mature optimization but in our case, we probably want to make sure that we …

PLATFORM-826 Add head support & integration tests for vignette routes

---

src/vignette/http/middleware.clj
src/vignette/http/routes.clj
test/vignette/http/middleware_test.clj

@drsnyder 
https://wikia-inc.atlassian.net/browse/PLATFORM-896
Adds middleware to replace multiple slashes with a single slash. These account for ~5% of our `bad-request-path` errors.

replace multiple slashes in :uri with a single slash

---

src/vignette/util/image_response.clj
test/vignette/util/image_response_test.clj

@drsnyder 
https://wikia-inc.atlassian.net/browse/PLATFORM-1053
Looks like a `Content-Disposition` header with quotes containing a comma (ex: `Content-Disposition: inline; filename="some_filename\"with,stuff\""`) cause a duplicate header problem in Chrome. Trick seems to be to return a literal `\"` back, which means escaping the quote to be `\\\"` :/

commas in quotes in content-disposition header

---

src/vignette/http/legacy/route_helpers.clj
src/vignette/http/legacy/routes.clj
src/vignette/http/route_helpers.clj
src/vignette/http/routes.clj
src/vignette/util/external_hotlinking.clj
test/vignette/http/route_helpers_test.clj

https://wikia-inc.atlassian.net/browse/PLATFORM-1121
@drsnyder 
Looks like the functionality to force a thumbnail is only happening for legacy URLs. I also made sure the `X-Vignette-Force-Thumb` header is being properly created by Varnish.

call force-thumb? for Vignette-style urls

---

.gitignore
src/vignette/http/middleware.clj
test/vignette/http/middleware_test.clj

Read the full story in https://wikia-inc.atlassian.net/browse/PLATFORM-966
Cache images for 14 days on both CDN and client level
With `s-maxage` being set to a value higher than `max-age` we were
getting lots of requests from clients trying to revalidate the image
because `Age` header (returned by CDN) was higher than `max-age` sent to
the client.
14 days will cover ~75% of images:
```
Age 5th percentile - 1.10 days
Age 10th percentile - 1.85 days
Age 25th percentile - 3.86 days
Age 50th percentile - 9.94 days
Age 75th percentile - 15.57 days
Age 90th percentile - 31.94 days
Age 95th percentile - 48.79 days
Age 99th percentile - 50.78 days
```
@nmonterroso / @drsnyder / @ljagiello

PLATFORM-966: cache images for 14 days

---

README.md
project.clj
src/vignette/core.clj
src/vignette/storage/core.clj
test/vignette/storage/core_test.clj

Added `:cache-thumbnails` to storage core and the command line interface. When this toggle is true, thumbnails will not be read from nor written to the backing storage. They will always be generated at request time.
https://wikia-inc.atlassian.net/browse/SERVICES-367
/cc @nmonterroso @ljagiello

Add a toggle for caching thumbnails in vignette

---

src/vignette/util/thumbnail.clj

Add counter for thumbnail generation and thumbnail cache hits. This will give us more insight into how often we are using the backing cache for thumbnails.
/cc @ljagiello @nmonterroso

Add counters for thumbnail generation

---

src/vignette/http/middleware.clj
test/vignette/http/routes_test.clj

After deploying to prod some healthchecks started failing as well as 404's were not handled correctly.
This PR fixes that issue
@macbre

Fix route concatenation in image routes

---

src/vignette/setup.clj
test/vignette/http/routes_test.clj

```hlr/legacy-routes``` return list of routes which in turn caused all following routes to be overriden.
This change fixes concatenation of routes list so instead of list like:
```[ route_a route_b [sub_a sub _b] ]```
We get ```[route_a route_b sub_a sub_b]```
Previous change was doing the same but it only fixed tests :disappointed:. Here I also make tests use vignette.setup as a source of sample routing configuration which aligns it with how production is configured.
@macbre @michalroszka

Second attempt at fixing Routing concatenation

---

src/vignette/storage/s3.clj
src/vignette/util/filesystem.clj
src/vignette/util/thumbnail.clj
test/vignette/storage/s3_test.clj

Without proper filename suffix both Tika/Pantomime and Imagick mime detection failed to work properly especially for SVG images.
This change reintroduces filename suffix in temp file and allows for both detection to correctly handle SVG files.

PLATFORM-1541 Add original filename suffix to temporary file && fix Mime detection

---

README.md
src/vignette/util/thumbnail.clj
test/vignette/util/thumbnail_test.clj

After #101 some files without extension failed to thumbnail properly
Additionally I included fix for PLATFORM-1265 by just copying the original if specified mime has been encountered.
I believe that if vignette is not able to crop certain files then it should at pass them unmodified. As 'best' effort' to serve the content.

PLATFORM-1644 PLATFORM-1265 Fix thumbnails for videos

---

src/vignette/storage/static_assets.clj
src/vignette/util/consul.clj
src/vignette/util/thumbnail.clj
test/vignette/util/thumbnail_test.clj

Some badly uploaded avatars currently have empty file names.
This allows to handle those edge cases.

PLATFORM-1643 Allow handling of avatars without any name in metadata

---

bin/thumbnail

Due to some bug (either ImageMagick or broken image) convert process  sometimes never finish and consuming 100% of CPU. Timeout should help for that and kill process after 5 min.
/cc @drsnyder @nmonterroso @pchojnacki

PLATFORM-1584: Timeout for hanging convert

---

bin/thumbnail

`identify` version 6.9.0-4 started to output a separate entry per each animation frame instead of a single value when run using the following command line:
`identify -format %n ....`
The change solves the issue and handles both old and new output correctly.
/cc @pchojnacki

Fix detecting animated GIFs after output format of identify has changed

---

bin/thumbnail

Theoretically behavior for "top-crop-down" and "zoom-crop-down" was unspecified when requested dimensions were smaller than those of the original image. Practically the output was a cropped image but the image dimensions ratio was changed in a non-intuitive (and non-practical) way.
This change brings a bit more of sanity into this use case. The highest priority in the current implementation is to preserve the ratio of the requested dimensions.
https://wikia-inc.atlassian.net/browse/PLATFORM-1805
/cc @drsnyder @nmonterroso @SzymonCierniewski @pchojnacki

PLATFORM-1805: Fix top-crop-down when requested size is smaller than original image

---

src/vignette/setup.clj
src/vignette/storage/static_assets.clj
src/vignette/util/image_response.clj
src/vignette/util/services.clj
src/vignette/util/static_assets.clj
test/vignette/storage/static_assets_test.clj
test/vignette/util/image_response_test.clj
test/vignette/util/services_test.clj

To allow more flexibility in review process we decided to implement filtering of rejected static-asset images in vignette.
This change makes static-assets handling code to at the same time ask two services then resolve both responses  asynchronously and check if both services return proper responses.
Additionally, static assets images were missing SurrogateKey which this change also adds.
/cc:
@drsnyder @nmonterroso

PLATFORM-1331 Make vignette ask Image review service for static-assets images status

---

src/vignette/util/thumbnail.clj
test/vignette/util/filesystem_test.clj
test/vignette/util/thumbnail_test.clj

some junk filenames caused junk file extension to be used on filesystem.
This PR fixes it by only allowing ([a-z_A-Z0-9]*) in file extension otherwise the extension will be treated as nil.

PLATFORM-1808 Fix file extension handling 

---

src/vignette/util/thumb_verifier.clj
test/vignette/util/thumb_verifier_test.clj

[Ticket](https://wikia-inc.atlassian.net/browse/SER-81)
This PR fixes the rounding error issue (too many false positives in error log) and introduces the `area_ratio` field for easier log filtering.

SER-81 thumb verifier rounding error fix

---

src/vignette/http/middleware.clj
src/vignette/http/routes.clj

Logging the details of the requests so we can check (based on the accept headers and user agents) what % of the request could accept webp format.
@pwojcik86

PLATFORM-2660: log request details (path, format, image size, headers))

---

src/vignette/http/middleware.clj
src/vignette/http/routes.clj

Reverts Wikia/vignette#119
Reverting as logging was eventually implemented in VCL (https://github.com/Wikia/wikia-vcl/pull/1185 and https://github.com/Wikia/chef-repo/pull/12330)

Revert "PLATFORM-2660: log request details (path, format, image size, headers))"

---

README.md
src/vignette/http/route_helpers.clj
src/vignette/storage/static_assets.clj
test/vignette/storage/static_assets_test.clj

https://wikia-inc.atlassian.net/browse/SER-753
Adds a new optional query parameter `bp` that must contain a `static-assets` image id. If the requested `static-assets` image is blocked, Vignette will return the placeholder instead. All requested transformations will be applied to the placeholder.
//cc @Wikia/services-team

SER-753 placeholders for blocked images

---

src/vignette/storage/local.clj
src/vignette/util/thumbnail.clj

Revert some old changes in order to fix the thumbnailer results uploads to s3.
We were hooking into stream close event to upload the files from `/tmp/vignette` to s3. Unfortunately that stream is not closed when the response is server, so the only scenario in which the images were uploaded was when the object were garbage-collected early enough (before the files were removed from `/tmp` which happens every 10 minutes).
In this change I'm uploading the files to s3 in parallel to serving the response. As a results I cannot delete the file from `/tmp` in the code, but those are cleaned up anyway by a cron job.

PLATFORM-2892: Fix uploading thumbnailer results back to s3

---

bin/thumbnail
test/vignette/http/integration_test.clj

For now we will just use quality level 90 for PNGs being converted to WebP and see if we get better results.
ping: @Wikia/core-platform-team

PLATFORM-2894: Setting quality for converting PNGs into WebP to 90

---

src/vignette/util/external_hotlinking.clj
src/vignette/util/thumbnail.clj
test/vignette/http/route_helpers_test.clj
test/vignette/http/routes_test.clj
test/vignette/util/thumbnail_test.clj

This removes some of the duplicated checks. Also optimizes the performance for full size images, as previously we were downloading the originals regardless if the converted `webp` version was available in s3 cache.

Platform-2899: Simplify the flow for full-size images

---

src/vignette/util/thumbnail.clj
test/vignette/http/route_helpers_test.clj
test/vignette/util/thumbnail_test.clj

Some of the jpg&png files are stored without an extension. When generating thumbnails, use the actual content type to make a decision about serving webp.

PLATFORM-2920: Detect original image content type base on content, not on extension

---

bin/thumbnail

*WORK IN PROGRESS*
Fixes:
* `svg_preoptions` has to be called before `thumb_params`, because for some modes `thumb_params` removes the `$IN` variable, which is needed by `svg_preoptions`
* if `$HEIGHT` is set to `":auto"`, we cannot use it as integer when calculating SVG density
Sample url that will be fixed by this PR: http://vignette3.wikia.nocookie.net/logopedia/images/thumb/2/2e/Seven_logo.svg/125px-0%2C379%2C0%2C395-Seven_logo.svg

PLATFORM-2995: fixing SVG images

---

src/vignette/util/thumbnail.clj

If thumbnailer script runs for longer than 5 seconds, log the thumbnailing details so we can investigate performance issues with some of the images

PLATFORM-2995: Log slow thumbnailer runs

---

.travis.yml
bin/thumbnail

Test animated gif - `s3://dragonsdogma/images/7/7c/Skill_Magick_Archer_Magick_Rebalancer.gif`
With old settings:
```
➜  gif_test time /opt/imagemagick-7.0.5/bin/convert test.gif -limit memory 256MB -limit map 256MB -limit disk 1024MB -limit thread 2 -limit time 120 -auto-orient -coalesce -thumbnail 670x375^ -gravity center -background none -extent 670x375 -layers Optimize test-7.0.5.gif
convert: DistributedPixelCache '127.0.0.1' @ error/distribute-cache.c/ConnectPixelCacheServer/242.
convert: cache resources exhausted `test.gif' @ error/cache.c/OpenPixelCache/3631.
convert: DistributedPixelCache '127.0.0.1' @ error/distribute-cache.c/ConnectPixelCacheServer/242.
convert: cache resources exhausted `test.gif' @ error/cache.c/OpenPixelCache/3631.
convert: DistributedPixelCache '127.0.0.1' @ …
```

Higher memory limit (performance boosts)

---

k8s/k8s_descriptor-poz-dev.yaml
k8s/k8s_descriptor-res-prod.yaml
k8s/k8s_descriptor-sjc-dev.yaml
k8s/k8s_descriptor-sjc-prod.yaml

https://wikia-inc.atlassian.net/browse/SER-2562
I wasn't able to adjust threads and queue size to a point where the app wouldn't eventually restart, but the new values do increase time under load. It seems that JVM memory is constantly rising without any significant GC.
@Wikia/services-team

SER-2562 | reduce threads and request queue

---

src/vignette/util/image_response.clj
test/vignette/util/image_response_test.clj

`X-Surrogate-Key` - Fastly doesn't support such header (they use `Surrogate-Key`. We want to cleanup this custom header (it's not used by our caches).

OPS-12119: X-Surrogate-Key header cleanup
